[build]
  publish = "dist"   
  command = "npm run build" 

[context.deploy-preview]
  branch = "option-1"  

[context.deploy-preview]
  branch = "option-2"  

[context.deploy-preview]
  branch = "option-3"  

[context.deploy-preview]
  branch = "*"  
